# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: customers_service_development

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: customers_service_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  adapter: oracle_enhanced
  username: <%= ENV['ORACLE_USER'] %>
  password: <%= ENV['ORACLE_PASSWORD'] %>
  database: <%= ENV['ORACLE_SID'] %>
  host: <%= ENV['ORACLE_HOST'] %>
  port: <%= ENV['ORACLE_PORT'] %>

# Oracle configuration (for production with Oracle)
# Uncomment and configure when deploying to Oracle database
# Note: Requires activerecord-oracle_enhanced-adapter and ruby-oci8 gems
#
# oracle_default: &oracle_default
#   adapter: oracle_enhanced
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *oracle_default
#   username: <%= ENV['ORACLE_USER'] || 'customers_dev' %>
#   password: <%= ENV['ORACLE_PASSWORD'] || 'password' %>
#   host: <%= ENV['ORACLE_HOST'] || 'localhost' %>
#   port: <%= ENV['ORACLE_PORT'] || 1521 %>
#   database: <%= ENV['ORACLE_SID'] || 'XEPDB1' %>
#
# test:
#   <<: *oracle_default
#   username: <%= ENV['ORACLE_TEST_USER'] || 'customers_test' %>
#   password: <%= ENV['ORACLE_TEST_PASSWORD'] || 'password' %>
#   host: <%= ENV['ORACLE_HOST'] || 'localhost' %>
#   port: <%= ENV['ORACLE_PORT'] || 1521 %>
#   database: <%= ENV['ORACLE_TEST_SID'] || 'XEPDB1' %>
#
# production:
#   <<: *oracle_default
#   username: <%= ENV['ORACLE_USER'] %>
#   password: <%= ENV['ORACLE_PASSWORD'] %>
#   host: <%= ENV['ORACLE_HOST'] %>
#   port: <%= ENV['ORACLE_PORT'] %>
#   database: <%= ENV['ORACLE_SID'] %>
